### ISSUE TITLE
Home screen - icon panel is incomplete

### ISSUE THREAD

**Issue by sives** [sives/Plio#35]
The Standards icon panel is missing its lower panel - the metrics panel area - the one which says "8 standards, 2 new" in the UI prototype

**Comment by sives** [comment]
Display "8 standards" in Milestone 2b, display the "2 new" part in Milestone 3 - agreed

**Comment by Praxie** [comment]
https://trello.com/c/4ct3YeY9/145-i35-bug-home-screen-icon-panel-is-incomplete

**Comment by Praxie** [comment]
@sives how do you like this idea? (It's a mockup)
![screen shot 2016-05-19 at 12 40 45 pm](https://cloud.githubusercontent.com/assets/2095940/15389351/13f7a7c4-1dbf-11e6-8fbe-8ccd8c628cd3.png)

**Comment by Praxie** [comment]
We can mark the standard as 'viewed' after the user opened the information card. The 'new' label will disappear right after the user will select a standard.

**Comment by sives** [comment]
Yes - I like this idea.

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/115

**Comment by sives** [comment]
The count of the number of Compliance Standards and the number of new standards is not correct.  In the Clifton organization there are 9 standards in the Compliance Standards screen, and none are new (to my user) but the icon indicator on the Home screen is indicating 10 standards, 1 new.

**Comment by RevelsGit** [comment]
That's because it was counting deleted standards too. It is already fixed in dev. https://i.gyazo.com/e82c15b8f1b389c60b5a11ac0006ef02.gif

**Comment by sives** [comment]
Counting still doesn't work.  Try adding a new standard as steve.ives@pliohub.com, then log out and login as steve@hoverkey.com.   I added one new standard and the system thought I had entered 5 new standards.

**Comment by Praxie** [comment]
@sives I can't reproduce this bug.

**Comment by sives** [comment]
Probably my mistake in testing.
