### ISSUE TITLE
User screen - missing user in LHS list view

### ISSUE THREAD

**Issue by sives** [sives/Plio#42]
I deleted a user profile (Hoverkey Steve, email address steve@hoverkey.com) then added it back by issuing and accepting and verifying a new invitation.  Although I can login as Hoverkey Steve and even show the User profile card for Hoverkey Steve, this user no longer displays in the LHS List View in the user directory, even when I am logged in  as that User.

**Comment by Praxie** [comment]
Copy that. 
We need to remove the "isDeleted: true" status of the user that has been invited again to the organization.

**Comment by Praxie** [comment]
Fixed during #23

**Comment by sives** [comment]
This bug is still there.  I can still log on as steve@hoverkey.com and go to the User Directory, and I am still not listed.

**Comment by sives** [comment]
Fixed
